/**
 * generated by Xtext 2.14.0
 */
package br.usp.ffclrp.dcm.lssb.restaurant.analysisactivitydescription.textualdsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AnalysisActivityDSLIdeModule extends AbstractAnalysisActivityDSLIdeModule {
}
